Light Mode Switch
ContentWarnings/WebFrontend pull request #36
Opened 2023-04-04 04:56 UTC by nategaulke

# What changed?
Light and dark mode now controlled by toggling (automatically set to dark mode if preference not previously stored)

# How was this accomplished?
Theme Context Created, Switch on AccountSettings

# Testing
`npm start`

# Related Issues or Work Items
Closes #26

2023-04-04 14:35 UTC, jeffreydivi commented
> automatically set to dark mode if preference not previously stored
Can we have it set to the user's current OS setting and/or have an auto-sync setting (the "old" behavior)?

Relevant JS for detecting Dark Mode: `(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches)`

2023-04-04 14:41 UTC, jeffreydivi requested changes

2023-04-04 14:41 UTC, jeffreydivi commented on src/context/ThemeContext.js
> +    return "dark";
Return `(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? "dark" : "light"` instead if theme is `null`, unless we want to add an "auto" switch to sync with OS settings.

2023-04-05 21:29 UTC, nategaulke commented
Now set up to use the user's default when first loaded or when user selects that option in settings.

2023-04-06 20:48 UTC, Quikks1lver approved these changes

2023-04-06 20:52 UTC, merged